# @name getToken
POST http://192.168.56.104:8484/auth/realms/bustvs_realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=bustvs_client&grant_type=password&scope=openid&username=user1&password=user1user1

###
@auth_token = {{getToken.response.body.$.access_token}}

GET http://localhost:8080/api/fares
Authorization: Bearer {{auth_token}}
Content-Type: application/json