server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: "/api"

spring:
  application.name: ${APPLICATION_NAME:bus-tvm}
  # Database connection settings
  datasource:
    username: what
    password: whatwhat
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.56.104:5432/bus_system
  # JPA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
#      ddl-auto: validate
#    show-sql: true
    properties:
      hibernate:
        default_schema: bus_tvm

keycloak:
  auth-server-url: http://192.168.56.104:8180/auth
  realm: bustvm_realm
  resource: bustvm_client
  public-client: true

# Log
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data: INFO
    org.pringframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate: DEBUG
